Add `prepend` for TupleN
vavr-io/vavr pull request #2627
Opened 2021-01-10 13:46 UTC by EntryPointKR

Added the `prepend` in TupleN template.

After we can use:
```
<T> Tuple0.prepend(T t0) = Tuple1<T>
<T> Tuple2<A, B>.prepend(T t0) = Tuple3<T, A, B>
```

2021-01-11 13:19 UTC, danieldietrich requested changes
Thank you @EntryPointKR,

your PR looks good to me but I have one request for change:

I recognized that the index '0' of the parameters `T0 t0` is unnecessary because tuples always start with index 1. Therefore I would choose the simpler `T t` instead for all prepend methods. Could you change that please?

And you are right, the parameters of the append method should also not have an index to be in line with the prepend method. Therefore I would change `append(Tn tn)` (for n = 0...8) to `append(T t)`. Could you please also do that in another PR?

Many thanks for your support!

\- Daniel

2021-01-19 18:38 UTC, danieldietrich approved these changes

2021-01-19 18:40 UTC, danieldietrich commented
Hi @EntryPointKR,
I approved the PR now and will perform cross-cutting rename operations of generics and args in a separate PR.
Thx!

2021-01-19 18:40 UTC, merged

2021-01-19 22:06 UTC, EntryPointKR commented
@danieldietrich Sorry for not response to the request, I couldn't manage my time. Can I open the PR on weekend?

2021-01-19 23:30 UTC, danieldietrich commented
@EntryPointKR sure! Please don't feel bad in any way, I really appreciate your help!