solution for problem 44
vavr-io/vavr pull request #2685
Opened 2021-09-26 21:52 UTC by smthelusive

solution for euler problem 44: 
https://projecteuler.net/problem=44

2021-11-01 00:25 UTC, cal101 commented on src/test/java/io/vavr/collection/euler/Utils.java
> +    static Stream<Long> pentagonal() {
The t._1 is only based on t._2.
_2 is 1 2 3 4
So they can be split into Stream.from and map.

2021-11-01 00:36 UTC, cal101 commented on src/test/java/io/vavr/collection/euler/Euler44Test.java
> +    private Long minimalPentagonalDiff() {
I like the idea of looping over the sum.
Just a few remarks.
You are generating two pentagonal streams. From what i understand vavr streams  are just lazy but can be
Iterated over multiple times.
So we should be able to define a variable pentagonals in method and use that twice. It should be possible to do it in a single expression, not sure how.
Replacing the compareTo with a simple "x < y" would make it more readable IMO.

2021-12-07 15:46 UTC, danieldietrich requested changes
Hi @smthelusive 👋,
thank you, great solution!
Could you please take a look at the review comments?
Thank you :)

2021-12-07 15:46 UTC, danieldietrich commented on src/test/java/io/vavr/collection/euler/Euler44Test.java
> +                Utils.pentagonal().takeWhile(pentagonal -> sumPentagonal.compareTo(pentagonal) > 0)
Yes, @cal101 is right, `sumPentagonal.compareTo(pentagonal) > 0` can be simplified by `sumPentagonal > pentagonal`

2021-12-07 15:46 UTC, danieldietrich commented on src/test/java/io/vavr/collection/euler/Utils.java
> +                .map(t -> t._1);
@cal101 could you provide the implementation you suggested? That way @smthelusive can verify if the test is still green...

2022-02-19 11:37 UTC, danieldietrich commented
Thank you Nataliia! I will merge it now to go forward.
@cal101 we can do any improvements in a subsequent PR...

2022-02-19 11:37 UTC, merged